// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_6hF5IejfTSaUA-bDtmguEWS-Q22cmfY',
    appId: '1:104655464548:web:461ecf1fe2fbad1a9f5771',
    messagingSenderId: '104655464548',
    projectId: 'ashesibus-6a47c',
    authDomain: 'ashesibus-6a47c.firebaseapp.com',
    storageBucket: 'ashesibus-6a47c.appspot.com',
    measurementId: 'G-1L335BX3YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwtpF-kXpNdOtPplA5T0ddz-GvK8tTFTs',
    appId: '1:104655464548:android:21701638cf41a70a9f5771',
    messagingSenderId: '104655464548',
    projectId: 'ashesibus-6a47c',
    storageBucket: 'ashesibus-6a47c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf72zerPtWOQrfDSdSfv0kKlCg8nB7Rwo',
    appId: '1:104655464548:ios:c8431aad84aa8bd49f5771',
    messagingSenderId: '104655464548',
    projectId: 'ashesibus-6a47c',
    storageBucket: 'ashesibus-6a47c.appspot.com',
    iosBundleId: 'com.example.ashesiBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf72zerPtWOQrfDSdSfv0kKlCg8nB7Rwo',
    appId: '1:104655464548:ios:c8431aad84aa8bd49f5771',
    messagingSenderId: '104655464548',
    projectId: 'ashesibus-6a47c',
    storageBucket: 'ashesibus-6a47c.appspot.com',
    iosBundleId: 'com.example.ashesiBus',
  );
}
